name: Metrics embed

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Lucastirbat
          config_timezone: Europe/Bucharest
          config_output: metrics.svg
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_limit: 12

